### ISSUE TITLE
New ios13 modal, cancel issue

### ISSUE THREAD

**Issue by rodolphefauquez** [payjp/payjp-react-native-plugin#50]
Hello. First, thank you for this RN library!

With iOS 13 (tested on 13.3), the form does not appear full screen anymore, i guess because of new ios13 changes on uiviewcontroller. Problem is, we can dismiss the modal by swipping it with top-to-bottom gesture, and "onCardFormCanceled" is not triggered in that case.

![Simulator Screen Shot - iPhone 7 - 2020-04-16 at 11 09 01](https://user-images.githubusercontent.com/9111635/79406819-f7794100-7fd2-11ea-9ada-996348885f49.png)

Also, could be possible to have an option to get the fullscreen mode?

Thank you!

**Comment by yatatsu** [comment]
Hi @rodolphefauquez, thanks for your feedback!
We reproduced that "onCardFormCanceled" is not called when the CardFormViewController is dismissed by swipping it with top-to-bottom gesture.
It is due to missing delegate, and we will fix this in next release soon.

> Also, could be possible to have an option to get the fullscreen mode?

Anyway, it's nice feature request, thanks.

**Comment by yatatsu** [comment]
Now we released new version v0.3.0. Please try it. Thank you.

https://github.com/payjp/payjp-react-native-plugin/releases/tag/v0.3.0

**Comment by rodolphefauquez** [comment]
That was fast! It's working now. Thanks of lot.
